---
services:
  mysql:
    container_name: tp_docker_db
    image: mysql:8.0.39
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=spring_sec_ex2
    ports:
      - 6033:3306
    # volumes:
    #   - todo_db:/var/lib/mysql
      # - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    # networks:
    #   - todo_network

  pma:
    container_name: tp_docker_db_admin
    image: phpmyadmin:latest
    depends_on:
      - mysql
    ports:
      - 3030:80
    # environment:
    #   - PMA_HOST=tp_docker_db
    # networks:
    #   - todo_network

  backend:
    container_name: tp_docker_spring_app
    build: ./
    links:
      - mysql
    depends_on:
      - mysql
    restart: always
    ports:
      - 8080:8080
    command: 
      - --spring.datasource.url=jdbc:mysql://tp_docker_db/spring_sec_ex2
      - --spring.jpa.hibernate.ddl-auto=validate
    # networks:
    #   - todo_network

# volumes:
#   todo_db:
# networks:
#   todo_network: